### ISSUE TITLE
Adding an An FAQ page ( Frequently Asked Question page)

### ISSUE THREAD

**Issue by ManpreetSingh18** [BamaCharanChhandogi/Diabetes-Prediction#10]
I can add an FAQ section to explain to users how to calculate DPF, blood pressure, BMI, the objective of the project, how to use it, and many other things about the project, helping to resolve common queries from people.It will be something like the example below:
![Screenshot 2024-05-28 014105](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/72294811/f020fa8a-a023-491b-9d29-60a68d8889fb)

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
