### ISSUE TITLE
🐞[Bug]: Adding of a 404-Error Page

### ISSUE THREAD

**Issue by AkshitGarg24** [BamaCharanChhandogi/Diabetes-Prediction#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To ensure a positive user experience, a custom 404 error page should be created and displayed when a user navigates to a non-existent or incorrect web address. This page should provide a friendly message and useful navigation links.

### Expected behavior

Mentioned above.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
I just wanted to let you know I don't need it now.
