### ISSUE TITLE
🐞[Bug]:  Correct Color of 'Back-To-Top' Button According to Website Theme and Appearing Time

### ISSUE THREAD

**Issue by AsmitaMishra24** [BamaCharanChhandogi/Diabetes-Prediction#111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The 'Back-To-Top' button on our website currently does not match the overall color scheme of our theme and is always visible, which can be distracting. This issue needs to be addressed to improve visual coherence and user experience.

Current Behavior:-
1. The 'Back-To-Top' button appears in a color that is not part of our primary or secondary color palette.
2. The button is always visible, regardless of the user's scroll position.

### Expected behavior

1. The 'Back-To-Top' button should seamlessly integrate with the rest of the website’s design.
2. The color should be adjusted to match our website's theme colors.
3. The button should only become visible after the user has scrolled down a certain distance from the top of the page.

### Add ScreenShots

![Screenshot 2024-06-20 003132](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/146121869/18fadd26-8ba6-4acc-b782-42c3f63fa070)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.
