### ISSUE TITLE
💡[Feature]: Adding a about page

### ISSUE THREAD

**Issue by anwesha2002** [BamaCharanChhandogi/Diabetes-Prediction#117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a about page which shows some basic information about diabetes and this website(like  factors affecting, symptoms etc, and how this website is measuring that )

### Use Case

I think this is necessary because that will increase the transparency of the website more and the user will be able to trust the website more for the accurate prediction.

### Benefits

This will be beneficial to understand the terms mentioned in the form to fill up for the prediction
![Screenshot 2024-06-25 025331](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/116761608/802aab50-8097-41e8-a892-efd68f1d3d69)
There is no mention of the term or the full form of the abbreviation which may not be understandable for the user

### Add ScreenShots

@BamaCharanChhandogi i am a gssoc'24 contributor. please assign this to me.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
#113

**Comment by anwesha2002** [comment]
@BamaCharanChhandogi okay, is it done or else I also can work on in
