### ISSUE TITLE
🐞[Bug]: home page needs to be responsive 

### ISSUE THREAD

**Issue by kapilG0** [BamaCharanChhandogi/Diabetes-Prediction#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Home page needs to be responsive 

### Expected behavior

![Screenshot_20240625_232521](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/59639410/ae54de9b-2515-4764-a896-f310695c2f0f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by kapilG0** [comment]
Hello @BamaCharanChhandogi please assign this issue to me under gssoc 24

**Comment by BamaCharanChhandogi** [comment]
We are working on this issue in another PR
