### ISSUE TITLE
🐞[Bug]: Social media Icons are not aligned. 

### ISSUE THREAD

**Issue by Amishachoudhary22** [BamaCharanChhandogi/Diabetes-Prediction#123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The social media icons on the webpage are not aligned properly. They appear unevenly spaced and misaligned, affecting the overall aesthetic and user experience of the webpage.

### Expected behavior

The social media icons should be evenly spaced and aligned horizontally or vertically, depending on the design. They should have consistent margins and padding, providing a neat and organized appearance.

### Add ScreenShots

<img width="440" alt="Screenshot 2024-06-26 at 10 31 25 AM" src="https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/103454929/9a01d887-81b1-445e-9363-a4e4fb8fe542">

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
Do not need to change. It's fine.
