### ISSUE TITLE
📝[Docs]:  Enhance Readme

### ISSUE THREAD

**Issue by ananyag309** [BamaCharanChhandogi/Diabetes-Prediction#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

I am aiming to enhance readme by adding gssoc label, creating a secion feature in, adding some more css to readme.

### Suggested Change

This will be nice 
![Capture read](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/145869907/6233d402-8bc7-4d1d-b0f3-06e46991f96e)

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ananyag309** [comment]
@BamaCharanChhandogi thankyou sir for assigning me this issue. I want to work under gssoc so can you please add gssoc and level label too.
