### ISSUE TITLE
💡[Feature]: Add Terms and Conditions Page

### ISSUE THREAD

**Issue by AsmitaMishra24** [BamaCharanChhandogi/Diabetes-Prediction#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add a Terms and Conditions page to our diabetes prediction website to clearly outline the rules and regulations for using our service. This page will help protect our website and inform users about their responsibilities and rights.

Terms and Conditions Content:
1. Usage guidelines for the website and its services.
2. Information about intellectual property rights.
3. Limitation of liability clauses.
4. User account responsibilities.
5. Termination of use policy.
6. Governing law and dispute resolution.
7. Contact information for any queries related to the terms.

Navigation:
1. Add a link to the Terms and Conditions page in the website footer.
2. Optionally, add a link in the main navigation menu.

Design Considerations:
1. Ensure the page is user-friendly and accessible.
2. The page should be responsive and function well on both desktop and mobile devices.

### Use Case

1. Legal Protection: The website needs to clearly state the terms under which it operates to protect against potential legal issues.
2. User Agreement: Users need to understand and agree to the terms before using the website's services.
3. Dispute Resolution: In the event of a dispute, the terms and conditions provide a reference point for resolution.
4. Service Clarity: Users are informed about what they can and cannot do on the website, ensuring a better user experience.

### Benefits

1. Legal Protection: Helps protect the website from legal claims and disputes.
2. User Clarity: Provides clear guidelines for users about what is expected of them.
3. Trust Building: Enhances transparency and trust with users by clearly stating the rules and regulations.
4. Risk Management: Reduces the risk of misuse of the website and its services.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
I do not need this, see you in another issue/PR.
