### ISSUE TITLE
💡[Feature]:  Adding more social media icons 

### ISSUE THREAD

**Issue by jayanththalla** [BamaCharanChhandogi/Diabetes-Prediction#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the footer, some social media icons are not there.
I want add the icons to the footer

### Use Case

Adding more social media icons they can share easily

### Add ScreenShots

![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/121346142/5f8bcf16-a91b-4266-b74a-511782c38c4f)

Please assign me @pa
### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
Don't need it.
