### ISSUE TITLE
Adding the icons 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [BamaCharanChhandogi/Diabetes-Prediction#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding the icons for different sections such as home , data info etc:- on the navbar

### Use Case

This would enhance the overall look of the website.

### Add ScreenShots

![Screenshot 2024-07-08 172541](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/117037441/a9788c8a-484d-40e0-a08b-aaf0048d0b37)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
Don't need it.
