### ISSUE TITLE
💡[Feature]: overlapping of the text in the main-page.

### ISSUE THREAD

**Issue by AnkitLuhar** [BamaCharanChhandogi/Diabetes-Prediction#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

there is overlapping of the text in the main page of the webpage ,which shows a  unregularity in the styling  ,its affect the user-interaction and also its seem like there is not seo optimiztion.

### Use Case

website first impression is ui/ux design so , we have to maintain the design.

### Add ScreenShots

![Screenshot (870)](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/142730608/285a9c4c-6ceb-40a8-85cb-d3d250e04458)

Assign this issue under the Gssoc 24.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by AnkitLuhar** [comment]
@BamaCharanChhandogi assign this issue and within one-hour i will open the PR under code of conduct of the project and also add some css to give user better experience if its look like it is needed.

**Comment by malvika-sinha** [comment]
I want to resolve the issue, Kindly assign me the task
