### ISSUE TITLE
[Feat]: Add a floating back to top button

### ISSUE THREAD

**Issue by Asymtode712** [BamaCharanChhandogi/Diabetes-Prediction#28]
I wish to add a floating button which on clicked will scroll back to top.

![float btn](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/115717746/aa3dc53c-4b2d-4ec7-b884-9923f8f117b6)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Asymtode712** [comment]
@BamaCharanChhandogi please assign me this issue
