### ISSUE TITLE
[Feat]: Adding social media and quick links

### ISSUE THREAD

**Issue by Asymtode712** [BamaCharanChhandogi/Diabetes-Prediction#34]
The links are not redirecting properly

![q](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/115717746/558fa8a6-2f2b-4b22-878b-f048bd3e61d7)

I wish to fix this

@BamaCharanChhandogi please assign me this issue

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.
