### ISSUE TITLE
[Feat]: NavBar should close When Navitem is clicked in mobile devices

### ISSUE THREAD

**Issue by SrinivasDevolper** [BamaCharanChhandogi/Diabetes-Prediction#43]
**Actual Behaviour:**
NavBar is not closed close When Nav Item is clicked on mobile devices

https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/121508628/8d0bcae0-ca7d-4579-938f-bf61dbaa1355

**Excepted Behaviour:**
 NavBar should close When Navitem is clicked on mobile devices

**I am GSSOC24 Contributor
please assign me this issue, I would like to work on it**

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
