### ISSUE TITLE
[Bug] Updating Favicon

### ISSUE THREAD

**Issue by its-kumar-yash** [BamaCharanChhandogi/Diabetes-Prediction#44]
I will change the vite icon to a better-looking icon.
Kindly assign this to me.

![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/97521394/a82cb992-3d67-4d22-b89c-532c331c0041)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.
