### ISSUE TITLE
Improving the home page

### ISSUE THREAD

**Issue by Athul28** [BamaCharanChhandogi/Diabetes-Prediction#46]
![Screenshot 2024-05-30 225105](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/79209367/8d4ac0c3-0138-45da-9767-cfc534a24537)

The home page text looks small and also the bg image doesn't match with the theme of the project I can improve it by adding the right image that describes the website and also improve the texts

Also I will add new favicon instead of vite logo favicon

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
Hi, Favicon Issue is already here: #44. You can improve the Home page. I will be happy to merge.

**Comment by Athul28** [comment]
@BamaCharanChhandogi thanks for assigning the task, I will improve the home page. If u have any other specific stuffs to be changed please do say me.

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will fix the task.
