### ISSUE TITLE
Adding a "Contact Us" Page

### ISSUE THREAD

**Issue by AkshitGarg24** [BamaCharanChhandogi/Diabetes-Prediction#5]
The website currently lacks a dedicated "Contact Us" Page. The website should include a dedicated "Contact Us" page. This page should provide the organization's email, contact number, and address, as well as a contact form for users to reach out.

**Comment by AkshitGarg24** [comment]
@BamaCharanChhandogi Please add the label "level" to this issue.

**Comment by Gauravdevlo** [comment]
I would like to work please assign this to me.

**Comment by BamaCharanChhandogi** [comment]
Hi @Gauravdevlo, 
I think  @AkshitGarg24 working on this issue. You can raise a new issue and work on that.
