### ISSUE TITLE
Enhancing Contact Us Page

### ISSUE THREAD

**Issue by its-kumar-yash** [BamaCharanChhandogi/Diabetes-Prediction#52]
The background of the Contact Us page is just plain white; I'll add some gradients or background images to make it more attractive. 

Kindly assign this issue to me.

![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/97521394/099fbc68-6a2e-4445-b36b-29ce769e1541)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by its-kumar-yash** [comment]
Hi @BamaCharanChhandogi, Please check this out. should I finalize this?

![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/97521394/299921dc-8038-478d-b135-7e1e62c3ed88)

**Comment by its-kumar-yash** [comment]
also, I think, this background should be applied to all the pages. to maintain the consistency of the website.

**Comment by BamaCharanChhandogi** [comment]
You can raise PR. I will check then I will decide.
