### ISSUE TITLE
[Feature] Adding Custom Scrollbar

### ISSUE THREAD

**Issue by SwanandD121** [BamaCharanChhandogi/Diabetes-Prediction#58]
**Description:**
The platform currently lacks the functionality of theme-matching scrollbar which are pivotal for improving user comfort and navigation fluidity. By integrating this feature, I aim to provide users with a smoother and more personalized browsing experience.

I have implemented this feature multiple times in open source as well as personal projects, so please assign this issue to me under GSSoC'24.

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by SwanandD121** [comment]
Thanks for assigning me this issue. Please label this as **Level 1/2/3**
@BamaCharanChhandogi
