### ISSUE TITLE
[Bug] Errors in Contribution.md file.

### ISSUE THREAD

**Issue by SwanandD121** [BamaCharanChhandogi/Diabetes-Prediction#61]
In the [Contribution.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTION.md) file, the contributing steps seem to be given for some other project. It says to create gaming files while your website dosen't have any content related to gaming.

It needs to change as soon as possible as some contributors might end up following that which could possibly ruin the original project.

I propose to solve this error by modifying the file with reference to the Diabetes Prediction project. Please assign me this issue under GSSoC'24.

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.
