### ISSUE TITLE
Website using nb.pkl pre-trained model for prediction  but in ipynb file there is no naive bayes algorithm

### ISSUE THREAD

**Issue by ranamanish674zu** [BamaCharanChhandogi/Diabetes-Prediction#66]
Actually when i was working at #57 then i see in py file there are website using nb.pkl in flask , but when i see the ipynb file then there is no naive bayes model which is trained over there. We have to make the naive bayes model then after that we can use it using pkl.
![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/119676300/2b56073b-e5a9-4085-b772-61437216776b)
here  saving the model naive bayes but there is no naive bayse algorithm exists over there , there is only SVM,KNN,Decision Trees,Random Forest ...used 
![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/119676300/16d75328-46cd-4907-8f63-9fd221f2c462)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by ranamanish674zu** [comment]
@BamaCharanChhandogi if possible assign it to me , i want to work on it

**Comment by ranamanish674zu** [comment]
@BamaCharanChhandogi sir could you pleaes see this isssue?
