### ISSUE TITLE
Navbar not responsive

### ISSUE THREAD

**Issue by sharmi4590** [BamaCharanChhandogi/Diabetes-Prediction#67]
The content in the navbar is coming out of the navbar, I would like to fix it.
![Screenshot (522)](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/102676949/93b2730b-2456-4fbe-b32a-98c2d2b5543d)
![Screenshot (523)](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/102676949/1cfc2b64-29ed-4281-a1f0-a624af7f272f)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by Samik123Mit** [comment]
pls assign me the issue,i will fix the task.

**Comment by sharmi4590** [comment]
@BamaCharanChhandogi Could you please assign me this

**Comment by BamaCharanChhandogi** [comment]
> @BamaCharanChhandogi Could you please assign me this
> 

I think it's already resolved.

**Comment by sharmi4590** [comment]
> > @BamaCharanChhandogi Could you please assign me this
> 
> I think it's already resolved.

No It is not yet solved , this is the recent screenshot 
![Screenshot (632)](https://github.com/user-attachments/assets/7389d9e7-7d71-4396-8169-02ce5b6000ca)
