### ISSUE TITLE
Adding a 404 not found Error page for your website 

### ISSUE THREAD

**Issue by ManpreetSingh18** [BamaCharanChhandogi/Diabetes-Prediction#70]
When a user clicks on a page that is not defined an Error page should come to tell them and give option to redirect to the Home Page
Current scenario
[
![Screenshot 2024-06-02 133642](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/72294811/6b464213-3d3a-4845-9b78-394f2cf7ff59)
](url)
Expected result
![Screenshot 2024-06-02 133744](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/72294811/3cca1437-b789-4826-ab52-97d07c6c0a46)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
I think it will not make any sense, so I am closing this issue.
