### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by sanskriti-lal** [BamaCharanChhandogi/Diabetes-Prediction#86]
<img width="1321" alt="Screenshot 2024-06-07 at 10 08 02 AM" src="https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/165655543/797852b6-5a5b-4b3f-a760-5303392d801d">
Better UI for the main page. Adjust the text in a manner to make it more attractive. 
I'm a GSSoC'24 contributor, efficient in Web development and UI/UX design. Can you please assign this work to me.

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by sanskriti-lal** [comment]
<img width="726" alt="Screenshot 2024-06-07 at 11 19 07 AM" src="https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/165655543/6689017c-cbbb-4dc6-af25-446ff631c98d">
<img width="728" alt="Screenshot 2024-06-07 at 11 19 16 AM" src="https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/165655543/cd8ced77-e48c-4e82-8787-1fca86c01f94">
I can update the design according to your choice, as per the above two. Or if you don't prefer these I can suggest other alternative UI's as well, according to your requirements.

**Comment by BamaCharanChhandogi** [comment]
Hi @sanskriti-lal,
Thank you for raising this issue. I think the first one is better. There is no need to add a numbered section. We can work on the first one.

**Comment by sanskriti-lal** [comment]
Ok cool. I've made a PR can you please look into it.
