### ISSUE TITLE
Not responsive on every standard screen size

### ISSUE THREAD

**Issue by AdityaKumar-Git** [BamaCharanChhandogi/Diabetes-Prediction#87]
This website is not responsive for the standard tablet screen size i.e., ```768x575```. Please assign me the task to make it responsive also add the labels neccessary.

![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/154753771/51d8f66b-e0f4-4b9f-afd9-4a88fe73b8db)

![image](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/assets/154753771/5fd64b4e-b876-4a51-b874-734230ed4131)

**Comment by BamaCharanChhandogi** [comment]
Thank you for creating this issue! 🎉 We'll look into it as soon as possible. In the meantime, please make sure to provide all the necessary details and context. If you have any questions or additional information, feel free to add them here. Your contributions are highly appreciated! 😊

You can also check our [CONTRIBUTING.md](https://github.com/BamaCharanChhandogi/Diabetes-Prediction/blob/main/CONTRIBUTING.md) for guidelines on contributing to this project.

**Comment by BamaCharanChhandogi** [comment]
I think the problem is in the navbar. so we can fix it.

**Comment by malvika-sinha** [comment]
I want to resolve the issue, Kindly assign me the task

**Comment by BamaCharanChhandogi** [comment]
It's resolved actually.
